### ISSUE TITLE
My votes export

### ISSUE THREAD

**Issue by OndrejZamazal** [okgreece/Alignment#25]
Currently, a user can see all "my votes". Since voting could help with constructing linksets, it would be good to also add an option "export" linksets according to votes from a project perspective. One option could be to export them with computed confidence based on voting.

**Comment by skarampatakis** [comment]
I understand the first part. 

Actually by design, links that have upvote - downvote > 0 are marked as published and get published on SPARQL Endpoint, with the help of D2R.

A filter will be added to select links from specific available project.   

Another option could be to export links as files or on endpoint based on voting result, by a threshold defined by user. [TODO]

But I am confused on this:

> One option could be to export them with computed confidence based on voting.

By "computed confidence" what do you mean? Similarity scores? 

Thank you in advance.

**Comment by OndrejZamazal** [comment]
I just meant a ratio of votes in favour divided by all votes. But maybe for some offline work absolute numbers of upvotes and downvotes could also be useful. This depends on a scenario. Sometime people only want a linkset with full consensus, in another use case majority vote is enough.

**Comment by skarampatakis** [comment]
Thank you for your response. Maybe export should be configurable giving some options like you mentioned to cover all needs.

**Comment by skarampatakis** [comment]
Fixed on develop/1 branch and working on demo server.

Now you can select the project to export, format and threshold. Threshold is computed by upvotes/total votes ratio.
