### ISSUE TITLE
Preview does not work during voting

### ISSUE THREAD

**Issue by OndrejZamazal** [okgreece/Alignment#58]
In 'My Votes' during voting there is always pop-up option 'Preview' at subject, predicate and object, but  there is no content in the preview after clicking on it.

**Comment by skarampatakis** [comment]
This actually at the moment depends on whether IRIs are dereferenceable. That's because there are cases were the whole descriptions of the resources are not uploaded on the platform. Let it be vote only projects etc. 

Perhaps I could change this behaviour to merge descriptions in case of empty results from dereferencing.
